// Slide content for posts 1–3 (from posts.md), using real palettes from seasons.json.
export default (S) => {
  const hex = (id, name) => S[id].palette.find((c) => c.name.toLowerCase().includes(name))?.hex;
  const cta = (title, hl) => ({ title, cta: true, v: { t: "mock", id: "soft-autumn", hl } });
  return [
    {
      n: 1,
      caption:
        "Your colour season isn't a vibe. It's temperature, value, contrast and saturation.\nSeasonal colour analysis is those four questions. Season Card measures all four from a selfie, right in your browser. 🎨\nWhich one do you think is your strongest trait? 👇\n\nFree scan at seasoncard.app Save this to explain seasons to a friend.",
      tags: "#coloranalysis #colouranalysis #seasonalcoloranalysis #colortheory #colorseason",
      slides: [
        { hook: true, title: "Your colour season isn't a vibe. It's 4 measurements.", v: { t: "numbered" } },
        { kicker: "1 · Undertone", title: "Does your skin lean warm (golden) or cool (pink / blue)?", v: { t: "gradient", pos: 64 } },
        { kicker: "2 · Depth", title: "How light or deep are your skin, hair and eyes together?", v: { t: "value" } },
        { kicker: "3 · Contrast", title: "How different are they from each other?", v: { t: "heads" } },
        { kicker: "4 · Chroma", title: "Do clear, bright colours suit you, or soft, muted ones?", v: { t: "chroma" } },
        { kicker: "Mix all 4", title: "…and you land in 1 of 12 seasons.", body: "Colour theory calls it value, temperature and saturation.", v: { t: "grid12" } },
        cta("Get your 4 numbers free."),
      ],
    },
    {
      n: 2,
      caption:
        "\"Is this why I always look tired in black?\" Maybe, maybe not. Black is simply the deepest, highest-contrast neutral there is.\nIf your colouring is softer, a near-black often does the same job with less shadow. Which swap are you trying? 🖤\n\nFind out if black is your colour. Free scan at seasoncard.app",
      tags: "#coloranalysis #colorseason #wintercolors #softautumn #styletips",
      slides: [
        { hook: true, title: "Is black really “bad” on you?", v: { t: "black" } },
        { title: "Short answer: black isn't bad. It's **very deep + very high contrast.**", v: { t: "black", tags: ["Depth: max", "Contrast: max"] } },
        { title: "In seasonal theory, pure black lives mostly in the **Winter** palettes.", v: { t: "rows", ids: ["deep-winter", "true-winter", "bright-winter"] } },
        { title: "With **softer or lighter** colouring, black can cast shadows near the face.", v: { t: "shadow" } },
        { kicker: "Autumns, swap it for", title: "Espresso · dark chocolate · deep olive", v: { t: "swatches", list: [["#4B2E20", "Espresso"], ["#3B2A20", "Dark chocolate"], ["#4A4A2A", "Deep olive"]] } },
        { kicker: "Summers, swap it for", title: "Charcoal · deep navy · slate", v: { t: "swatches", list: [["#3A3D42", "Charcoal"], ["#1F2A44", "Deep navy"], ["#5A6573", "Slate"]] } },
        { kicker: "Springs, swap it for", title: "Warm navy · chocolate · dark teal", v: { t: "swatches", list: [["#26355E", "Warm navy"], ["#5A3A28", "Chocolate"], ["#1F5C5C", "Dark teal"]] } },
        cta("Still love black? Wear it away from your face. Find your “black” →"),
      ],
    },
    {
      n: 3,
      caption:
        "Soft and True Autumn wear the same family of colours: rust, olive, camel, teal. True Autumn wears them rich. Soft Autumn wears them as if a little grey was mixed in. Save for shopping 🍂\n\nSave this. Free scan at seasoncard.app to see your chroma score.",
      tags: "#softautumn #trueautumn #coloranalysis #autumnpalette #colorseason",
      slides: [
        { hook: true, title: "Soft Autumn or True Autumn? The one difference.", v: { t: "fans", a: "soft-autumn", b: "true-autumn" } },
        { title: "Both are **warm.** The difference is **chroma**: how saturated the colour is.", v: { t: "chroma", a: "#C0632A", b: "#B08A70", la: "Rich", lb: "Muted" } },
        { kicker: "Soft Autumn", title: "Warm-neutral, medium, low contrast, **muted**", v: { t: "swatches", list: S["soft-autumn"].cardSwatches.map((c, i) => [c, ["Clay", "Honey", "Sage", "Soft teal"][i]]) } },
        { kicker: "True Autumn", title: "Warm, medium-deep, **rich and earthy**", v: { t: "swatches", list: S["true-autumn"].cardSwatches.map((c, i) => [c, ["Rust", "Mustard", "Olive", "Teal"][i]]) } },
        { kicker: "Same colour, two versions", title: "Orange", v: { t: "pair", a: ["#C98B6B", "Soft Autumn"], b: ["#D2691E", "True Autumn"] } },
        { kicker: "Same colour, two versions", title: "Green", v: { t: "pair", a: ["#9FA37E", "Soft Autumn"], b: ["#6D6A2F", "True Autumn"] } },
        cta("Not sure which you are? Your chroma score tells you.", "Chroma"),
      ],
    },
      {
      n: 5,
      caption: "The \"sage green everything\" trend isn't for everyone, and that's fine. Every season has *a* green. Which one have you been reaching for? 🌿\n\nFind your green. Free scan at seasoncard.app",
      tags: "#sagegreen #coloranalysis #softsummer #softautumn #colorseason",
      slides: [
        { hook: true, title: "Sage green looks grey on some people. Here's why.", v: { t: "single", c: "#9CAF88" } },
        { title: "Sage is **soft** (low chroma), **light-medium**, and slightly **warm-neutral.**", v: { t: "chroma", a: "#9CAF88", b: "#5FA36A", la: "Sage (soft)", lb: "Clear green" } },
        { kicker: "Best on", title: "Soft Autumn and Soft Summer", v: { t: "palettes", ids: ["soft-autumn", "soft-summer"] } },
        { kicker: "Good on", title: "Light Summer and Light Spring, in a lighter tint", v: { t: "pair", a: ["#9CAF88", "Sage"], b: ["#C5D1B8", "Light sage"] } },
        { kicker: "Tricky for", title: "Bright Winter and Bright Spring. It can look dusty next to clear colouring.", v: { t: "palettes", ids: ["bright-winter", "bright-spring"] } },
        { kicker: "Their green instead", title: "Bright seasons → mint or jade. Deep seasons → deep olive or forest.", v: { t: "swatches", list: [["#98E0C2", "Mint"], ["#00A36C", "Jade"], ["#4A5D23", "Deep olive"], ["#2F4F2F", "Forest"]] } },
        cta("Which green is yours? Your 36-colour palette is in the full report."),
      ],
    },
    {
      n: 6,
      caption: "This is a big reason people get different seasons from different quizzes, apps, even analysts working from photos. Light changes everything. Get the light right and the result gets more consistent. 💡\n\nSave the checklist. Try the free scan by a window at seasoncard.app",
      tags: "#undertone #coloranalysis #skinundertone #colorseason #lighting",
      slides: [
        { hook: true, title: "Warm in one photo, cool in the next? Your skin didn't change.", v: { t: "faces", tints: [["rgba(255,170,90,.35)", "Warm bulb"], ["rgba(110,150,210,.35)", "Shade"]] } },
        { title: "**Warm bulbs** push skin yellow-orange, so everyone looks warm.", v: { t: "faces", tints: [["rgba(255,160,70,.45)", "illustration"]] } },
        { title: "**Shade and overcast** push skin blue, so everyone looks cool.", v: { t: "faces", tints: [["rgba(100,140,210,.45)", "illustration"]] } },
        { title: "**Phone cameras auto-correct** white balance, and beauty filters change skin.", v: { t: "bigtext", text: "WB · AUTO", sub: "Your camera guesses the light, and often guesses wrong." } },
        { title: "Screens differ too. The same photo looks different on two phones.", v: { t: "pair", a: ["#C98B6B", "Phone A"], b: ["#C6977F", "Phone B"] } },
        { kicker: "Best light", title: "Indirect daylight, facing a window, no direct sun.", v: { t: "bigtext", text: "☀︎ → 🪟 → you", sub: "Window in front of you, not behind." } },
        { kicker: "Checklist", title: "Before any colour analysis:", v: { t: "checklist", items: ["No filter", "No (or light) makeup", "Hair visible", "Facing a window"] } },
        cta("Season Card checks your light first, then it measures."),
      ],
    },
    {
      n: 7,
      caption: "\"Find her best pink\" videos keep going viral because the right pink changes everything. No faces needed: just figure out which family you're in. A, B, C or D? 👇\n\nComment your letter. Free scan at seasoncard.app to check.",
      tags: "#pink #coloranalysis #colorseason #springcolors #summercolors",
      slides: [
        { hook: true, title: "One of these pinks is yours. 🌸", v: { t: "letters", list: [["#FF8C7A", "A"], ["#C4A0A0", "B"], ["#C08081", "C"], ["#E0218A", "D"]] } },
        { title: "Myth: \"warm undertones can't wear pink.\" Truth: **every season has a pink.**", v: { t: "bigtext", text: "✕", sub: "\"Warm skin can't wear pink\"" } },
        { kicker: "A · Springs", title: "Warm coral-pink, peach-pink", v: { t: "swatches", list: [["#F4A2A0", "Peach-pink"], ["#FF8C7A", "Coral-pink"]] } },
        { kicker: "B · Summers", title: "Cool rose, soft raspberry, powder pink", v: { t: "swatches", list: [["#EBC3CC", "Powder"], ["#C4A0A0", "Cool rose"], ["#B03A5B", "Raspberry"]] } },
        { kicker: "C · Autumns", title: "Dusty rose-brown, terracotta pink", v: { t: "swatches", list: [["#C08081", "Dusty rose"], ["#B5705A", "Terracotta pink"]] } },
        { kicker: "D · Winters", title: "Icy pink or vivid fuchsia", v: { t: "swatches", list: [["#F4D7E3", "Icy pink"], ["#E0218A", "Fuchsia"]] } },
        cta("Guess your letter in the comments 👇 then check it free."),
      ],
    },
    {
      n: 8,
      caption: "Palette-only edition of \"guess her season\". How many did you get? Drop your score /4 👇 (No peeking at slide 6.)\n\nComment your score. Free Season Card at seasoncard.app",
      tags: "#guesstheseason #coloranalysis #colorseason #colorpalette #colouranalysis",
      slides: [
        { hook: true, title: "Guess the season from the palette alone. 🤔", v: { t: "bigtext", text: "?", sub: "4 palettes · answers on slide 6" } },
        { kicker: "Palette 1", title: "Guess!", v: { t: "letters", list: [["#F7C59F", ""], ["#9ED9CC", ""], ["#F5E1A4", ""], ["#F4A2A0", ""]] } },
        { kicker: "Palette 2", title: "Guess!", v: { t: "letters", list: [["#6D0F2B", ""], ["#000000", ""], ["#009B77", ""], ["#1B2A4A", ""]] } },
        { kicker: "Palette 3", title: "Guess!", v: { t: "letters", list: [["#7D8FA3", ""], ["#A28CA0", ""], ["#C4A0A0", ""], ["#9C8F87", ""]] } },
        { kicker: "Palette 4", title: "Guess!", v: { t: "letters", list: [["#B7410E", ""], ["#D4A017", ""], ["#708238", ""], ["#1F6F6B", ""]] } },
        { kicker: "Answers", title: "How many did you get?", v: { t: "answers", list: [[["#F7C59F", "#9ED9CC", "#F5E1A4", "#F4A2A0"], "Light Spring"], [["#6D0F2B", "#000000", "#009B77", "#1B2A4A"], "Deep Winter"], [["#7D8FA3", "#A28CA0", "#C4A0A0", "#9C8F87"], "Soft Summer"], [["#B7410E", "#D4A017", "#708238", "#1F6F6B"], "True Autumn"]] } },
        cta("Now get your own 4-colour card."),
      ],
    },
    {
      n: 9,
      caption: "If one quiz said Soft Summer and another said Soft Autumn, you may be right on the border. They're neighbours: same softness, same depth, same low contrast. The only real split is cool-neutral vs warm-neutral. That's why Season Card always shows a runner-up. Which side are you on? 🌫️🍂\n\nSee your runner-up season. Free scan at seasoncard.app",
      tags: "#softsummer #softautumn #coloranalysis #colorseason #undertone",
      slides: [
        { hook: true, title: "Soft Summer or Soft Autumn? It's one question.", v: { t: "fans", a: "soft-summer", b: "soft-autumn" } },
        { title: "Both are **soft, medium, low-contrast.** They're next-door neighbours.", v: { t: "palettes", ids: ["soft-summer", "soft-autumn"] } },
        { title: "The one question: **cool-neutral or warm-neutral?**", v: { t: "gradient", pos: 50, lo: "Cool-neutral", hi: "Warm-neutral" } },
        { kicker: "Soft Summer", title: "Cool-neutral, dusty, **grey-blue based**", v: { t: "swatches", list: S["soft-summer"].cardSwatches.map((c) => [c, S["soft-summer"].palette.find((p) => p.hex.toLowerCase() === c.toLowerCase())?.name ?? ""]) } },
        { kicker: "Soft Autumn", title: "Warm-neutral, earthy, **golden-grey based**", v: { t: "swatches", list: S["soft-autumn"].cardSwatches.map((c) => [c, S["soft-autumn"].palette.find((p) => p.hex.toLowerCase() === c.toLowerCase())?.name ?? ""]) } },
        { kicker: "Window test", title: "Camel vs dusty rose under your chin. Which one makes your skin look **more even?**", v: { t: "pair", a: [hex("soft-autumn", "camel") ?? "#B8946A", "Camel → Soft Autumn"], b: [hex("soft-summer", "dusty rose") ?? "#C49A9C", "Dusty rose → Soft Summer"] } },
        cta("Your result shows your season **and your runner-up**, because neighbours are close.", undefined),
      ],
    },
    {
      n: 11,
      caption: "Gold vs silver is the easiest undertone test you can do at home, and it beats staring at your veins. Daylight, no filter, foil under your chin. Which one won for you? 🥇🥈\n\nComment gold, silver or both. Free scan at seasoncard.app",
      tags: "#goldvssilver #undertone #coloranalysis #jewelry #colorseason",
      slides: [
        { hook: true, title: "Gold or silver? Try this, not the vein test.", v: { t: "swatches", list: [["linear-gradient(135deg,#8C6A1E,#E9C766 45%,#B8902C 60%,#F3DC8A)", "Gold"], ["linear-gradient(135deg,#7D8086,#E6E8EB 45%,#A3A7AD 60%,#F2F3F5)", "Silver"]] } },
        { title: "The vein test is unreliable. **Light, skin thickness and the room** all change what you see.", v: { t: "bigtext", text: "✕", sub: "\"Blue veins = cool, green veins = warm\"" } },
        { kicker: "Better test", title: "Hold **real gold and silver** (or foil) under your chin, facing a window.", v: { t: "checklist", items: ["Daylight, no direct sun", "No filter, bare skin", "One metal at a time", "Look at your skin, not the metal"] } },
        { title: "Gold makes your skin look **even and glowy?** Likely warm. Silver does it? Likely cool.", v: { t: "pair", a: ["linear-gradient(135deg,#8C6A1E,#E9C766 45%,#B8902C 60%,#F3DC8A)", "Even with gold → warm"], b: ["linear-gradient(135deg,#7D8086,#E6E8EB 45%,#A3A7AD 60%,#F2F3F5)", "Even with silver → cool"] } },
        { title: "**Both look fine?** You may be neutral. Rose gold and brushed metals are your friends.", v: { t: "single", c: "linear-gradient(135deg,#9A5A5E,#E6B2A6 45%,#B76E79 60%,#F1CFC6)", label: "Rose gold" } },
        { kicker: "Best metal, by season", title: "A few examples:", v: { t: "table", rows: [["#E9C766", "Soft Autumn", S["soft-autumn"].metals.best], ["#C9A24A", "Deep Autumn", S["deep-autumn"].metals.best], ["#C9CCD1", "Soft Summer", S["soft-summer"].metals.best], ["#E6E8EB", "Deep Winter", S["deep-winter"].metals.best]] } },
        { title: "Your full report lists your **best, good and skip** metals.", cta: true, v: { t: "mock", id: "soft-autumn", note: `Metals: ${S["soft-autumn"].metals.best} · skip ${S["soft-autumn"].metals.skip.toLowerCase()}` } },
      ],
    },
    {
      n: 12,
      caption: "Celebrity season debates are fun, but they show why photo-based typing is hard: stage lighting, dyed hair, makeup and editing all move the needle. Want a fairer read on yourself? Daylight, no filter. 💡\n\nFree scan at seasoncard.app. Use daylight!",
      tags: "#celebritycoloranalysis #coloranalysis #colorseason #undertone #beautytok",
      slides: [
        { hook: true, title: "Why can't the internet agree on celebrity colour seasons?", v: { t: "grid12" } },
        { title: "Same person, five comment sections, five different seasons. **Here's why.**", v: { t: "bigtext", text: "?", sub: "No photo can settle it." } },
        { kicker: "Reason 1", title: "**Stage and studio lighting** push skin warm or cool, photo to photo.", v: { t: "faces", tints: [["rgba(255,160,70,.45)", "Warm gel · illustration"], ["rgba(100,140,210,.45)", "Cool gel · illustration"]] } },
        { kicker: "Reason 2", title: "**Hair colour changes.** Dyed hair shifts contrast and warmth.", v: { t: "swatches", list: [["#E8DCC4", "Platinum"], ["#A63A1F", "Copper red"], ["#1E1612", "Jet black"]] } },
        { kicker: "Reason 3", title: "**Makeup and photo editing** change undertone and contrast.", v: { t: "bigtext", text: "EDITED", sub: "Retouching, filters, colour grading" } },
        { title: "So typing anyone from red-carpet photos is a guess. **That includes you from a filtered selfie.**", v: { t: "checklist", items: ["No filter", "No (or light) makeup", "Hair visible", "Facing a window"] } },
        cta("Unfiltered + daylight = your most consistent result. Try yours free."),
      ],
    },
    {
      n: 13,
      caption: "Burgundy season is here 🍷 but \"burgundy\" is really a range, from cool wine to warm oxblood. Both deep seasons can wear it; the temperature decides which one. Which side are you? Wine or brick?\n\nComment wine or brick. Free scan at seasoncard.app",
      tags: "#burgundy #deepautumn #deepwinter #coloranalysis #fallfashion",
      slides: [
        { hook: true, title: "Burgundy looks expensive on some people. On others: tired.", v: { t: "single", c: "#6D0F2B" } },
        { title: "Burgundy is **deep**, so both deep seasons can wear it. **Temperature** decides the version.", v: { t: "pair", a: [hex("deep-winter", "merlot"), "Cool wine"], b: [hex("deep-autumn", "oxblood"), "Warm oxblood"] } },
        { kicker: "Deep Winter burgundy", title: "Cool, berry, **wine**", v: { t: "swatches", list: [[hex("deep-winter", "merlot"), "Merlot"], [hex("deep-winter", "garnet"), "Garnet"], [hex("deep-winter", "cranberry"), "Cranberry"]] } },
        { kicker: "Deep Autumn burgundy", title: "Warm, brick, **oxblood-brown**", v: { t: "swatches", list: [[hex("deep-autumn", "oxblood"), "Oxblood"], [hex("deep-autumn", "mahogany"), "Mahogany"], [hex("deep-autumn", "brick"), "Brick"]] } },
        { kicker: "Lighter or softer colouring?", title: "Try a softened version: **raspberry** (Summer) or **rosewood** (Soft Autumn).", v: { t: "pair", a: ["#B03A5B", "Raspberry"], b: ["#9E5B5B", "Rosewood"] } },
        { kicker: "Quick check", title: "If burgundy makes your lips look pale, it's too deep. **Go one step lighter.**", v: { t: "pair", a: ["#6D0F2B", "Too deep?"], b: ["#9E3A4F", "One step lighter"] } },
        cta("Get your season's exact burgundy in your 36-colour palette."),
      ],
    },
  ];
};
